name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        sudo apt-get update && \
        sudo apt-get install -y python3-dev 
        pip3 install -U -r requirements.txt && \
        ./test_confused.py
